#!/usr/bin/env bash

client_port=`grep clientPort zoo.cfg|cut -d "=" -f 2`

host_ip=`hostname -i`

echo -n "zk://"

url=$(for container in `docker ps -q --filter "label=zookeeper=yes"`; do
    grep -E "^$client_port/tcp" <<<$(docker port $container) | grep -oE "[0-9]+$" | xargs -I {} echo -n "$host_ip:{},"
done)

sed 's|,$|/|' <<<$url
